### ISSUE TITLE
增加售票連結

### ISSUE THREAD

**Issue by ryudoawaru** [rubytaiwan/2016#34]
用途：擺放售票的 iframe

Example: https://5xruby.tw/talks/jquery-source 的右邊

![screenshot 2016-10-18 22 18 54](https://cloud.githubusercontent.com/assets/212290/19481552/eadb304c-9580-11e6-9bef-17be572b5d41.png)

**Comment by yayinchang** [comment]
Done: https://github.com/rubytaiwan/2016/pull/37

**Comment by ryudoawaru** [comment]
嵌進去有點醜，改 LINK 吧

**Comment by yayinchang** [comment]
Revise: https://github.com/rubytaiwan/2016/pull/40
