### ISSUE TITLE
Add gravatar avatar to staff list

### ISSUE THREAD

**Issue by ryudoawaru** [rubytaiwan/2016#43]
<img width="388" alt="screenshot 2016-10-20 19 58 21" src="https://cloud.githubusercontent.com/assets/212290/19558952/b7925cf8-96ff-11e6-9b82-eadd163d2094.png">

用 Gravatar 的大頭照取代這裡的寶石

**Comment by yayinchang** [comment]
沒有用過呢，所以我需要大家提供什麼才能讀取到大家的 Gravatar？

**Comment by elct9620** [comment]
http://www.asaph.org/p/gravatar.html

比較 Hardcode 的方法就是手動輸入信箱用生產器長出來網址 XD
（他是用信箱判斷的，只是會轉成一組 Hash 加密以免被人直接讀取到信箱位址）

**Comment by ryudoawaru** [comment]
手動輸入信箱，所以 yaml 裡加欄位吧

**Comment by elct9620** [comment]
這樣信箱就被公開拉 XDDD
會被寄垃圾信（？

存 Hash 過的覺得比較 Ok 拉

**Comment by ryudoawaru** [comment]
喔喔.......好像也是 XD  就醬吧 忘了 opensource

**Comment by yayinchang** [comment]
所以要跟所有 staff 收信箱的意思囉...XD
