### ISSUE TITLE
Speaker's photo is misaligned

### ISSUE THREAD

**Issue by juincc0** [rubytaiwan/2016#49]
<img width="500" alt="2016-10-25 17 27 37" src="https://cloud.githubusercontent.com/assets/8275168/19680476/6f8c0b66-9ad8-11e6-9f74-7c650fb25a06.png">

I think the one in the bottom should be aligned in the left?

**Comment by ryudoawaru** [comment]
@irene84111 覺得呢？

**Comment by yayinchang** [comment]
呃呃呀，因為目前 height 不一樣高，我用 flexbox 解決

**Comment by elct9620** [comment]
其實每三個就補 `</div><div class="row">` 就可以解決了⋯⋯

**Comment by yayinchang** [comment]
是沒錯啦，只是這樣好麻煩，還要用 JS 輔助？而且我已經修好了...
而且補 `.row` 會讓 responsive 壞掉吧？
