### ISSUE TITLE
Safari BUG

### ISSUE THREAD

**Issue by ryudoawaru** [rubytaiwan/2016#53]
![screenshot 2016-10-27 21 14 24](https://cloud.githubusercontent.com/assets/212290/19768549/7b84b8ba-9c8a-11e6-961c-ee28d18318a5.png)

Section 間有奇怪的一條線，Desktop Safari 限定

**Comment by yayinchang** [comment]
不只有 Safari 有這個問題 😂
調整了一下圖片，已經沒問題了！
Done：https://github.com/rubytaiwan/2016/pull/54

**Comment by elct9620** [comment]
這個應該是像素對齊問題，新的瀏覽器都支援 0.5px 的渲染，有時候沒對齊到就會變成這樣（遠望
