### ISSUE TITLE
Fixed scrolling while speaker profile opened

### ISSUE THREAD

**Issue by marsz** [rubytaiwan/2016#56]
http://recordit.co/iJzYRH7jxK

參考影片，注意右邊的捲軸
在打開一位講者的 profile 時，會下意識的想要往下捲看有沒有更多資料
結果就把背景的頁面給捲走 XD
關掉 profile 後發現原本的畫面跑掉了

**Comment by elct9620** [comment]
這個有點難，從以前到現在我好像都沒有看到什麼可以解決這個問題的好方法。

要來找一下資料了⋯⋯

**Comment by ryudoawaru** [comment]
這個的確是還好
